name: CI

on:
  push:
  pull_request:

defaults:
  run:
    shell: bash

concurrency:
    group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
    cancel-in-progress: true

permissions:
  contents: read

jobs:

  tests:
    name: Tests

    env:
      extensions: mbstring

    strategy:
      matrix:
        include:
          - php: '7.1'
          - php: '7.2'
          - php: '7.3'
          - php: '7.4'
          - php: '8.0'
          - php: '8.1'
      fail-fast: false

    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Configure environment
        run: |
          php -v
          PHP_VERSION=$(php -r "echo PHP_MAJOR_VERSION . '.' . PHP_MINOR_VERSION ;")
          echo $PHP_VERSION
          mkdir -p build/logs

      - name: Install dependencies
        run: |
          composer install -o -q --no-suggest

      - name: Run phpunit
        if: "matrix.php != '7.4'"
        run: |
          vendor/bin/phpunit

      - name: Run phpunit
        if: "matrix.php == '7.4'"
        run: |
          vendor/bin/phpunit --coverage-clover build/logs/clover.xml

      - name: Run coverage report
        if: "matrix.php == '7.4'"
        run: |
          php vendor/bin/coveralls -v
